### ISSUE TITLE
Doesn't work with meteor 1.1.0.3

### ISSUE THREAD

**Issue by avalanche1** [dalgard/meteor-viewmodel#15]
Works fine with 1.2.
But if I run 1.1 (which I run because it's far quicker on rebuilds) my whole project gets halted with this in console:
![image](https://cloud.githubusercontent.com/assets/10534563/10278640/d6b8db46-6b6f-11e5-961a-381794753b34.png)
I guess there are some package conflicts here. Version 1.2 compiler says that some es6 stuff is loaded - maybe the culprit is there...

**Comment by dalgard** [comment]
I'll fix this right away, thanks for reporting.

**Comment by dalgard** [comment]
Running the `/examples/all` project with Meteor version `1.1.0.3` (with platform packages replaced by `meteor-platform`), the problem doesn't occur.

What other packages does your project use?

**Comment by avalanche1** [comment]
```
meteor-platform
autopublish
insecure
accounts-password
coffeescript
mquandalle:jade
semantic:ui-css
meteorhacks:fast-render
dalgard:viewmodel
```

You can check it out here - https://github.com/avalanche1/test
It was actually for testing Manuel's viewmodel, but I've commented out all vm-related code and it still gives errors...
![image](https://cloud.githubusercontent.com/assets/10534563/10340175/f14531a6-6d1f-11e5-967e-7320ac6cbacb.png)

**Comment by dalgard** [comment]
I see it now. It didn't happen for me, because I use a local copy of the package – not the one on Atmosphere. I think it gets mangled somehow – the log says `viewmodel.es6.js.js`, which can't be right.

I'll have to ask about it in the forums.

https://forums.meteor.com/t/atmosphere-breaks-my-es6-package/11030

**Comment by dalgard** [comment]
There doesn't seem to be any progress on this issue, so I've made the decision to move the whole package forward to Meteor 1.2 – I know that this is a bummer for you, but it was going to happen eventually with version 1.0 of the package.

**Comment by avalanche1** [comment]
I see. I'll stick with 1.1 and Manuel's vm for now, until https://github.com/meteor/meteor/issues/5269 is alleviated.

**Comment by dalgard** [comment]
I can understand that – it's pretty frustrating with the long build times.
