### ISSUE TITLE
Improvements needed?

### ISSUE THREAD

**Issue by KoenLav** [dalgard/meteor-viewmodel#17]
Hi dalgard,

We're going to use your viewmodel instead of manuel's in one of our projects and I was wondering whether there are any improvements which need to be made? (Or are you content with the current feature set?)

I'd be happy to contribute.

**Comment by dalgard** [comment]
Thanks for your interest and for volunteering.

I'm actually quite content with the current API and feature set. What I find most powerful is creating custom bindings. I recommend using them for components and other functionality that should be encapsulated in a single element (take Pikaday as an example).

I don't expect there to be any more changes before version `1.0.0`, but still want to wait a bit before bumping it.

Your feedback will be welcome, together with any questions.

**Comment by KoenLav** [comment]
Thanks for your quick reply.

I'll be sure to let you know if we run into anything, but so far it's worked great!

**Comment by dalgard** [comment]
Will you be using Jade in your project?

The reason I'm asking is that my Jade fork, which has improved syntax for bindings, is currently a bit behind – I need to make some decisions about whether to follow `mquandalle`s version in regard to one or two features. Or whether to try to merge my improvements back into the main repo.

**Comment by KoenLav** [comment]
We will be using the default Blaze rendering engine.

**Comment by dalgard** [comment]
:+1:

**Comment by daveeel** [comment]
Hi @dalgard , I'm currently using Manuel's VM and your Jade package for using $b for Manuel's new binding syntax. Just curious, how much behind is your Jade fork? Ideally one Meteor Jade package is preferred.

**Comment by dalgard** [comment]
@daveeel: I _think_ that it's mainly one feature that has been added to `mquandalle`s package since I last pulled from it. I don't think there are any important bug fixes, but will have to look further into it.

I agree that one package is much preferred and will try to sync and possibly merge in the near future.
