### ISSUE TITLE
Shooting params into viewmodel functions

### ISSUE THREAD

**Issue by wvanooijen92** [dalgard/meteor-viewmodel#18]
Hi,

First of all, great project! 

I have a template named a with the following html:

```
<div class="col s2 center" {{bind "click: add -1"}}><i class="material-icons">remove</i></div>
```

In my JS i have:

```
    Template.a.viewmodel({
        add : function(e,quantity){
            console.log(quantity, parseFloat(quantity[1]));
        }
    }
```

Why is quantity an array? I expected it to be -1

Thank you!

**Comment by dalgard** [comment]
Thanks.

The second parameter in your method will be an array of the string arguments appended in the binding expression – and the third parameter will be an object with the keyword arguments passed to the `{{bind}}` helper.

You can write it like this:

``` js
Template.a.viewmodel({
  add(e, args) {
    let quantity = args[0];
    console.log(quantity, parseFloat(quantity));
  }
}
```

But better yet, pass the number using a keyword argument (either hardcoded or dynamically through a variable):

``` html
<div class="col s2 center" {{bind "click: add" quantity=-1}}><i class="material-icons">remove</i></div>
```

``` js
add(e, a, kwargs) {
  console.log(kwargs.quantity);
}
```

**Comment by dalgard** [comment]
Please close the issue if your problem has been solved.

**Comment by wvanooijen92** [comment]
Yes, ofc. Thanks for answering so quickly!
