### ISSUE TITLE
this.getData() - is non-reactive

### ISSUE THREAD

**Issue by comerc** [dalgard/meteor-viewmodel#24]
In API help:

```
// Reactively get the data context of the current template instance
this.getData();
```

In [source-code](https://github.com/dalgard/meteor-viewmodel/blob/73730289ee0d441e002895f861d84f205366f4ad/packages/dalgard_viewmodel/lib/viewmodel.js#L187-L190):

```
  // Reactively get the template's data context
  getData() {
    return this.templateInstance().data;
  }
```

According to Meteor's documentation, about [template.data](http://docs.meteor.com/#/full/template_data):

> This property provides access to the data context at the top level of the template. It is updated each time the template is re-rendered. Access is read-only and non-reactive.

**Comment by dalgard** [comment]
I'm actually a little unsure myself about _how_ the call to `templateInstance()` is reactive – when, exactly, is it invalidated? Anyway, I'm simply passing this reactivity on to the user of ViewModel.

**Comment by comerc** [comment]
We may use [Template.currentData()](http://docs.meteor.com/#/full/template_currentdata):

> Establishes a reactive dependency on the result.

Or not?

UPD:

> Uncaught Error: There is no current view

OK, we may use Template.currentData() in this cases with fields of Template.instance().viewmodel.

> - Inside an onCreated, onRendered, or onDestroyed callback, returns the data context of the template.
> - Inside an event handler, returns the data context of the template on which this event handler was defined.
> - Inside a helper, returns the data context of the DOM node where the helper was used.
