### ISSUE TITLE
Converting from manuel:viewmodel

### ISSUE THREAD

**Issue by zimt28** [dalgard/meteor-viewmodel#4]
`dalgard:viewmodel` and `manuel:viewmodel` both use the same `Template.$.viewmodel` syntax; so I can't have both in my app. But I'd like to move to your package step by step. How could I do that?

**Comment by dalgard** [comment]
Hmm, good point. I'll think about a solution.

I chose to use the same name as Manuel, because the name _really_ makes sense. But it's kind of inconvenient in this situation.

**Comment by dalgard** [comment]
Do you have any preferences as to the naming of the new `ViewModel` class and `viewmodel` hook during the migration?

Ideally, the name should be able to convey to new developers what is going on.

`ViewModel2` looks a bit too much like it's the next major version of the same library. `NewViewModel` doesn't really say anything. Maybe `DalgardViewModel` and `dalgardViewmodel` would be the least ambiguous choice...

**Comment by dalgard** [comment]
I finally arrived at the simplest possible solution and will be releasing a new version shortly, with the necessary steps described in the docs.

The steps are:
1. Make sure `dalgard:viewmodel` is included _before_ any package that exports a `ViewModel` and/or assigns something to `Blaze.Template.prototype.viewmodel`.
2. Reassign the relevant stuff to whichever names you like.

For example:

``` javascript
// E.g. /client/lib/dalgard-viewmodel.js
DalgardViewModel = Package["dalgard:viewmodel"].ViewModel;
Blaze.Template.prototype.dalgardViewmodel = DalgardViewModel.viewmodelHook;
```

**Comment by zimt28** [comment]
Great, thanks! I'll just try that! The name I'd use here is just `vm`, but it's a good solution to allow any!

**Comment by dalgard** [comment]
Whatever rocks your boat :) Kindly close the issue, once you've ascertained yourself that things are in order.

**Comment by zimt28** [comment]
Works fine :)

**Comment by dalgard** [comment]
Please note that in the next version `ViewModel.referenceName` is changed to `ViewModel.referenceKey`. Thanks.
