### ISSUE TITLE
Init function

### ISSUE THREAD

**Issue by zimt28** [dalgard/meteor-viewmodel#7]
Do you think it could make sense to add an `init` function next to `get` and `set`?
I just wrote a binding, which needs to hide/ show an element initially. I have a working solution, but I think that putting the code into an `init` function would be nicer:

``` coffeescript
ViewModel.addBinding 'slide', ->
  firstRun = true

  set: ($elem, new_value, args, kwhash) ->
    if firstRun
      if not new_value and $elem.is ':visible'
        console.warn 'To avoid flickering you should use CSS to hide the element', $elem.get(0), 'initially'
        $elem.hide()
      firstRun = false

    if new_value
      $elem.slideDown()
    else
      $elem.slideUp()
```

**Comment by dalgard** [comment]
I agree, I'm adding it in the next version.

**Comment by dalgard** [comment]
Added in `0.6.0`.
