### ISSUE TITLE
Please fix doc: "meteor install dalgard:viewmodel" ->"add"?

### ISSUE THREAD

**Issue by thearabbit** [dalgard/meteor-viewmodel#9]
Please fix doc: "meteor install dalgard:viewmodel" ->"add"?

**Comment by zimt28** [comment]
Why not make a PR? :)

**Comment by thearabbit** [comment]
Excuse me, I am not sure to use git.
(I afraid make a mistake).

**Comment by dalgard** [comment]
That's totally okay, pull requests on GitHub is mainly a feature of GitHub itself – it takes a little time to fork via GitHub, clone locally, commit, push, and then create pull request. It's a nice gesture, but I'm okay with correcting things.

Sorry for the slight delay, btw – corrected in `0.7.0`. I recommend updating, this version covers a few corner cases that broke before.

**Comment by thearabbit** [comment]
I will try `github`.

**Comment by thearabbit** [comment]
Thanks :+1:
